// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtCEzoClIXCqN3MCmamqxvMSJQes_zmNs',
    appId: '1:435034690665:web:87802d948840ed09917ef8',
    messagingSenderId: '435034690665',
    projectId: 'carelab-5c955',
    authDomain: 'carelab-5c955.firebaseapp.com',
    storageBucket: 'carelab-5c955.firebasestorage.app',
    measurementId: 'G-F31TPP7K36',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc7u0XiGSPGSeTdEWiffHneXNdhdtPZCo',
    appId: '1:435034690665:android:60c5676312d38089917ef8',
    messagingSenderId: '435034690665',
    projectId: 'carelab-5c955',
    storageBucket: 'carelab-5c955.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNOOHX5uriL6zB16wB3Na6kiPWMF_03jw',
    appId: '1:435034690665:ios:632e904fd41066e2917ef8',
    messagingSenderId: '435034690665',
    projectId: 'carelab-5c955',
    storageBucket: 'carelab-5c955.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNOOHX5uriL6zB16wB3Na6kiPWMF_03jw',
    appId: '1:435034690665:ios:632e904fd41066e2917ef8',
    messagingSenderId: '435034690665',
    projectId: 'carelab-5c955',
    storageBucket: 'carelab-5c955.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtCEzoClIXCqN3MCmamqxvMSJQes_zmNs',
    appId: '1:435034690665:web:3ee0e34443e58d66917ef8',
    messagingSenderId: '435034690665',
    projectId: 'carelab-5c955',
    authDomain: 'carelab-5c955.firebaseapp.com',
    storageBucket: 'carelab-5c955.firebasestorage.app',
    measurementId: 'G-XX7CWYZE5V',
  );
}
